// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtrnzafcmmwxizdkfkdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cm56YWZjbW13eGl6ZGtma2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzY2OTMsImV4cCI6MjA1OTgxMjY5M30.mXxCzIVZ9zQH81Vr0tppCEYsIJSCyqlwF7VTT6a9X4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);